config/routes.rb
Rails.application.routes.draw do

  get 'lessons/new'

  devise_for :users
  get 'static_pages/home'

  root 'static_pages#home'

  resources :users do
    resource :following, only: [:show]
    resource :followers, only: [:show]
  end
  resources :categories, only: [:index, :create, :destroy, :show, :edit, :update] do
    resources :lessons
  end
  resources :words, only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  namespace :admin do
    resources :categories, :users, :words
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @feed_items = current_user.feed.paginate page: params[:page]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if user_signed_in? %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <% unless current_user.admin? %>
      <%= link_to "Words", words_path, class: "btn btn-default list-words" %>
      <%= link_to "Lessons", categories_path, class: "btn btn-default list-lessons" %>
    <% end %>
    <section>
      <h3>Activities</h3>
      <%= render 'shared/feed' %> 
    </section>
  </div>
</div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to Fram gia E-learning system</h1>
  <h2>
    This is the home page for the
    <a href="http://www.framgia.vn/">Framgia</a>
    E-learning system.
  </h2>
  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>
<% end %>