config/routes.rb
Rails.application.routes.draw do

  get 'lessons/new'

  devise_for :users
  get 'static_pages/home'

  root 'static_pages#home'

  resources :users do
    resource :following, only: [:show]
    resource :followers, only: [:show]
  end
  resources :categories, only: [:index, :create, :destroy, :show, :edit, :update] do
    resources :lessons
  end
  resources :words, only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  namespace :admin do
    resources :categories, :users, :words
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :name, presence: true

  self.per_page = 5
end

app/controllers/admin/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :admin_user

  def index
    if current_user.admin?
      @category = Category.new
    end
    @categories = Category.paginate page: params[:page]
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Create new category successfully."
    else
      flash[:danger] = "Update category failed!"
    end
    redirect_to request.referrer || root_url
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = "Category updated"
      redirect_to request.referrer || root_url
    else
      redirect_to @category
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Category deleted"
    redirect_to categories_url
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end 

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.paginate page: params[:page]
  end
end

app/views/categories/_category.html.erb
<div class="panel panel-primary">
  <div class="panel-body">
    <div class="pull-left"><%= category.name %></div>
    <div class="pull-right">
      <%= link_to "Start", new_category_lesson_path(category), class: "btn btn-primary list-lessons" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<% provide(:title, 'Categories') %>
<h1>All categories</h1>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= render @categories %>
  </div>
</div>
<%= will_paginate %>