config/routes.rb
Rails.application.routes.draw do

  get 'lessons/new'

  devise_for :users
  get 'static_pages/home'

  root 'static_pages#home'

  resources :users do
    resource :following, only: [:show]
    resource :followers, only: [:show]
  end
  resources :categories, only: [:index, :create, :destroy, :show, :edit, :update] do
    resources :lessons
  end
  resources :words, only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  namespace :admin do
    resources :categories, :users, :words
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :word
  has_many :lesson_words

  validates :content, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :name, presence: true

  self.per_page = 5
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :lesson_words

  accepts_nested_attributes_for :lesson_words

  before_save :count_correct_answer

  private
    
    def count_correct_answer
      no_correct_answers = self.lesson_words.select{|result| result.answer == result.word.answers.find_by(is_right: true)}.count
      self.correct_answers = no_correct_answers
    end
end

app/models/lesson_word.rb
class LessonWord < ActiveRecord::Base
  belongs_to :word
  belongs_to :answer
  belongs_to :lesson
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, stretches: 20

  has_many :lessons, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  self.per_page = 10

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  # Returns a user's status feed.
  def feed
    if self.admin?
      Lesson.all
    else
      following_ids = "SELECT followed_id FROM relationships
                       WHERE  follower_id = :user_id"
      Lesson.where("user_id IN (#{following_ids})
                       OR user_id = :user_id", user_id: id)
    end
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :lesson_words

  accepts_nested_attributes_for :answers
  scope :not_learned, -> (user){where("id NOT IN (SELECT word_id FROM lesson_words 
                                WHERE lesson_id IN (SELECT id FROM lessons WHERE user_id = ?))", user.id)}
  scope :random_words, -> (user){Word.not_learned(user).order('RAND()').limit(30)}

  validates :category_id, presence: true
  validates :content, presence: true
end

app/controllers/admin/users_controller.rb
class UsersController < ApplicationController
  before_action :admin_user

  def index
    @users = User.paginate page: params[:page]
  end
  
  def show
    @user = User.find params[:id]
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to admin_users_url
  end

  private

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/admin/words_controller.rb
class WordsController < ApplicationController

  def index
    @words = Word.all
    @categories = Category.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user! 
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :full_name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.paginate page: params[:page]
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def show
    @title = "Followers"
    @user  = User.find params[:user_id]
    @followers = @user.followers.paginate page: params[:page]
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController

  def show
    @title = "Following"
    @user  = User.find params[:user_id]
    @followings = @user.following.paginate page: params[:page]
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  respond_to :js, :json, :html
  def new
    @category = Category.find params[:category_id]
    @lesson = @category.lessons.build user_id: current_user.id
    words = @category.words.random_words current_user
    20.times do |n|
      @record = @lesson.lesson_words.build
      @record.word = words[n]
    end
  end

  def create
    @category = Category.find params[:category_id]
    @lesson = @category.lessons.build lesson_params
    @lesson.user_id = current_user.id
    if @lesson.save
      redirect_to category_lesson_path(@category, @lesson)
    else
      render 'new'
    end
  end
  
  def show
    @category = Category.find params[:category_id]
    @lesson = Lesson.find params[:id]         
  end

  private

    def lesson_params
      params.require(:lesson).permit lesson_words_attributes: [:id, :word_id, :answer_id]
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :user_signed_in?
  
  def create
    user = User.find params[:followed_id]
    current_user.follow user
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow user
    redirect_to user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @feed_items = current_user.feed.paginate page: params[:page]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate page: params[:page]
  end
  
  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title page_title = ''
    base_title = "Ruby on Rails Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def gravatar_for user, options = {size: 80}
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Framgia Elearning", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>                
        <% if user_signed_in? %>
          <%= content_tag :li do
              link_to_if current_user.admin?, "Categories", admin_categories_path
            end
          %>
          <%= content_tag :li do
              link_to_unless(current_user.admin?, "Users", admin_users_path) do |name|
                link_to name, users_path
              end
            end
          %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> | Ruby on Rails</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to user_following_path(@user) do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  <% end %>
  <%= link_to user_followers_path(@user) do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.full_name %></h1>
<span><%= link_to "View my profile", current_user %></span>